version: '3'
services:

  kanban-app:
    build: ./kanban-app
    container_name: kanban-app
    environment:
      - DB_SERVER=database  # Use the name of the database service defined in the first compose file
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
    ports:
      - 8080:8080
    networks:
      - devnet
   
    

  kanban-ui:
    build: ./kanban-ui
    container_name: kanban-ui
    ports:
      - 4200:80
    links:
      - kanban-app
    networks:
      - devnet

networks:
  devnet:
  
# External network reference
networks:
  devnet:
    external:
      name: setup-dockerfile_setup-net
