version: '3'

services:
  dev:
    build: .
    container_name: dev
    ports:
      - "6001:6000"

  uat:
    build: .
    container_name: uat
    ports:
      - "6002:6000"

  prod:
    build: .
    container_name: prod
    ports:
      - "6003:6000"

  database:
    build: ./Database
    container_name: database
    volumes:
      - kanban-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      

volumes:
  kanban-data:
